// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An input device the user can choose (ADR-PROJ-004: everything is configurable).
 */
export type AudioDevice = { 
/**
 * The device's name, which is also its id: cpal has no stable device id, and a name is what the
 * user recognises anyway. A renamed or unplugged device therefore falls back to the default —
 * see [`Recorder::start`].
 */
name: string, 
/**
 * True for the system's default input device.
 */
is_default: boolean, };
