// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A built-in command, for the in-app reference (SSOT with the engine, ADR-PROJ-010).
 */
export type BuiltinCommandDto = { 
/**
 * The phrases that trigger it, as spoken.
 */
phrases: Array<string>, 
/**
 * `"line"`, `"paragraph"`, or `"punctuation"`.
 */
kind: string, 
/**
 * The character a punctuation command inserts; empty otherwise.
 */
inserts: string, 
/**
 * True for the opt-in punctuation set.
 */
punctuation: boolean, };
