// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a directory listing, for the in-app file picker (ADR-APP-026: the OS file dialog is a
 * native control we do not use — the picker is built from our own primitives instead).
 */
export type DirEntryDto = { 
/**
 * The entry's display name (the last path component).
 */
name: string, 
/**
 * The full path, for navigating into it or selecting it.
 */
path: string, 
/**
 * True for a directory, false for a file.
 */
is_dir: boolean, };
