// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntryDto } from "./DirEntryDto";

/**
 * A directory's contents plus where it sits, so the picker can render a list and a way back up.
 */
export type DirListingDto = { 
/**
 * The directory being listed.
 */
path: string, 
/**
 * Its parent, or `None` at a filesystem root.
 */
parent: string | null, 
/**
 * Directories first, then files, each alphabetical.
 */
entries: Array<DirEntryDto>, };
