// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether push-to-talk is actually armed — the difference between what the user asked for and what
 * the operating system granted.
 *
 * This exists because a dictation app whose only key silently does nothing is indistinguishable
 * from a broken one. The failure is **shown** (ADR-PROJ-004): nobody reads a log file.
 */
export type HotkeyStatus = { 
/**
 * The combination that was attempted, as the user sees it.
 */
shortcut: string, 
/**
 * True when the OS accepted the registration and holding the key will record.
 */
registered: boolean, 
/**
 * Why it is not armed, in words a user can act on. `None` when `registered` is true.
 */
error: string | null, };
