// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";
import type { JobState } from "./JobState";
import type { Progress } from "./Progress";

/**
 * One unit of slow work, as the UI sees it.
 */
export type Job = { id: bigint, kind: JobKind, 
/**
 * What the user reads. Never the recognised text — not even a snippet (ADR-PROJ-007).
 */
label: string, state: JobState, progress: Progress, 
/**
 * Milliseconds since the job started running.
 */
elapsed_ms: bigint, 
/**
 * Seconds remaining, or `None` when no honest estimate exists.
 */
eta_seconds: bigint | null, cancellable: boolean, 
/**
 * Why it failed, in words a user can act on. `None` unless the state is `Failed`.
 */
error: string | null, };
