// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of work a job is. The UI groups and labels by this; the log filters by it.
 */
export type JobKind = "model_download" | "model_verify" | "model_load" | "transcribe";
