// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a job is in its life. A job ends in exactly one of `Succeeded`, `Failed` or `Cancelled` —
 * and it always ends: a job left `Running` forever is the bug this enum exists to make visible.
 */
export type JobState = "queued" | "running" | "succeeded" | "failed" | "cancelled";
