// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model as the settings view sees it: what it is, and whether it is actually here.
 */
export type ModelStatus = { id: string, label: string, note: string, size_mb: bigint, multilingual: boolean, 
/**
 * True when the file is on disk **and** verified. A downloaded-but-unverified file does not
 * count as installed — that is the whole point of verifying it.
 */
installed: boolean, };
