// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model as the settings view sees it: what it is, and whether it is actually here.
 */
export type ModelStatus = { id: string, label: string, note: string, size_mb: bigint, multilingual: boolean, 
/**
 * True when the file is on disk **and** verified. A downloaded-but-unverified file does not
 * count as installed — that is the whole point of verifying it.
 */
installed: boolean, 
/**
 * True for a model the **user brought from disk** (ADR-PROJ-006). It is present and usable, but it
 * is **not verified** — there is no compiled-in hash for it — and the UI must say so. It is never
 * labelled "verified".
 */
imported: boolean, };
