// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far along a job is.
 *
 * `Determinate` carries the raw counts (bytes, samples, seconds) rather than a percentage: a
 * percentage discards the information the UI needs to render "412 MB of 1.5 GB", and it cannot be
 * used to compute a rate.
 */
export type Progress = { "kind": "indeterminate" } | { "kind": "determinate", done: bigint, total: bigint, };
