// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeChoice } from "./ThemeChoice";

/**
 * Persisted user preferences. Stored as JSON under `<app_data_dir>/settings.json`.
 *
 * Every field carries a serde default so a settings file written by an older version — missing a
 * newer field — still loads (the missing field falls back to its default) rather than failing to
 * parse and silently discarding the user's other preferences.
 */
export type SettingsDto = { 
/**
 * WebView zoom factor applied to the whole UI (ADR-APP-021). Clamped to [0.7, 1.6].
 */
ui_scale: number, 
/**
 * When true, closing the window keeps Huginn running in the system tray instead of quitting.
 *
 * **Default `true`, unlike the shell it was scaffolded from.** Huginn *is* a background tool: the
 * push-to-talk hotkey is the product, and it only works while the process lives. Quitting on a
 * window close would mean the user closes a window they no longer need and silently loses
 * dictation everywhere — the product would look like it worked and then stop, which is worse than
 * an app that never started.
 */
minimize_to_tray: boolean, 
/**
 * Light, dark, or follow the OS (default).
 */
theme: ThemeChoice, 
/**
 * The **interface** language (`"de"`, `"en"`). Not the language Huginn recognises — that one
 * comes with the model (ADR-PROJ-006).
 *
 * German is Huginn's first language, not a translation of an English original: the product is a
 * German dictation tool, and an untranslated key falls back to German rather than to a raw
 * identifier.
 *
 * A plain string, not an enum: adding a language must mean a new locale file plus one line in
 * the frontend — never a change to the IPC contract and a rebuilt backend.
 */
language: string, 
/**
 * The push-to-talk combination, in the shortcut syntax (`"Ctrl+Space"`, `"Ctrl+Shift+KeyJ"`).
 *
 * It is a *preference*, not a fact: the combination stored here may fail to register — another
 * application can already own it. Whether it is actually armed is [`HotkeyStatus`], and that is
 * what the UI must show the user (rule:overlay-and-input).
 */
hotkey: string, };
