// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which appearance the user wants (ADR-PROJ-003). `System` follows the OS setting and is the
 * default: an app that ignores the desktop's own light/dark choice is the one that stands out.
 */
export type ThemeChoice = "system" | "light" | "dark";
