// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceActionDto } from "./VoiceActionDto";

/**
 * A user-defined (or built-in) voice command (ADR-PROJ-010). Stored on-device in the settings.
 */
export type VoiceRuleDto = { 
/**
 * Stable id, generated when the rule is created; how the editor addresses it.
 */
id: string, 
/**
 * Trigger phrases, as spoken. Matched case-insensitively, punctuation-tolerant.
 */
phrases: Array<string>, action: VoiceActionDto, 
/**
 * Recognition languages this fires on: `["de"]`, `["en"]`, or `["*"]` for every language.
 */
languages: Array<string>, enabled: boolean, };
