// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a voice rule does (ADR-PROJ-010). Adjacently tagged so the frontend sees a clean union:
 * `{ kind: "line" } | { kind: "paragraph" } | { kind: "insert", template: string }`.
 */
export type VoiceActionDto = { "kind": "line" } | { "kind": "paragraph" } | { "kind": "insert", "template": string };
