// Shared governance library: parse ADR/rule/memory front-matter and (re)generate all indexes.
// Single source of truth for sync-index.mjs and check-index.mjs (ADR-005, ADR-007).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const ADR_DIR = path.join(ROOT, "docs", "adr");
export const RULES_DIR = path.join(ROOT, ".claude", "rules");
export const MEMORY_DIR = path.join(ROOT, ".claude", "memory");
// Project-owned governance line (ADR-030): indexed + validated by the same scripts, but NOT part of
// the pinned core manifest, so a project owns and freely changes these.
export const RULES_PROJECT_DIR = path.join(RULES_DIR, "project");
export const ADR_PROJECT_DIR = path.join(ADR_DIR, "project");
export const BLUEPRINT = path.join(ROOT, "docs", "agent-governance-blueprint.md");

export const LOAD_TIERS = ["core", "conditional", "archival"];
export const ADR_STATUSES = ["proposed", "accepted", "superseded", "deprecated"];
export const TLDR_MAX = 160;

const GENERATED_NOTICE = "<!-- GENERATED by scripts/sync-index.mjs — do not edit by hand. -->";

/** List `*.md` files in a directory, excluding the given basenames. Returns absolute paths, sorted. */
export function listMarkdown(dir, exclude = []) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md") && !exclude.includes(f))
    .sort()
    .map((f) => path.join(dir, f));
}

/** Parse one governance document. Returns { file, rel, data, body, hash }. */
export function parseDoc(file) {
  const raw = fs.readFileSync(file, "utf8");
  const { data, content } = matter(raw);
  const hash = crypto
    .createHash("sha256")
    .update(JSON.stringify(data) + "\n" + content.trim())
    .digest("hex")
    .slice(0, 16);
  // Normalise to POSIX-style forward slashes so the generated manifest is byte-identical across
  // OSes. `path.relative` yields backslashes on Windows, which made `manifest.json` flip-flop and
  // fail the staleness gate every time the repo was synced between macOS and Windows.
  const rel = path.relative(ROOT, file).split(path.sep).join("/");
  return { file, rel, data, body: content, hash };
}

/** Validate common front-matter. Returns an array of error strings (empty = ok). */
export function validateCommon(doc, { kind }) {
  const e = [];
  const d = doc.data;
  for (const field of ["id", "title", "tldr", "scope", "load"]) {
    if (d[field] === undefined || d[field] === null || d[field] === "") {
      e.push(`${doc.rel}: missing front-matter field '${field}'`);
    }
  }
  if (typeof d.tldr === "string" && d.tldr.length > TLDR_MAX) {
    e.push(`${doc.rel}: tldr is ${d.tldr.length} chars (max ${TLDR_MAX})`);
  }
  if (d.load && !LOAD_TIERS.includes(d.load)) {
    e.push(`${doc.rel}: invalid load '${d.load}' (expected ${LOAD_TIERS.join("|")})`);
  }
  // Reachability (rule:knowledge-handover, ADR-006): a `conditional` document is loaded ONLY when its
  // triggers or applies-to match the task. Declaring neither makes it unreachable — the knowledge is in
  // the repo but never reaches the agent who needs it, which is the same as not writing it down.
  if (d.load === "conditional") {
    const triggers = Array.isArray(d.triggers) ? d.triggers : [];
    const appliesTo = Array.isArray(d["applies-to"]) ? d["applies-to"] : [];
    if (!triggers.length && !appliesTo.length) {
      e.push(
        `${doc.rel}: unreachable — a 'conditional' document must declare 'triggers' or 'applies-to', otherwise no agent ever loads it.`,
      );
    }
  }
  if (kind === "adr") {
    if (!d.status || !ADR_STATUSES.includes(d.status)) {
      e.push(`${doc.rel}: invalid/missing status (expected ${ADR_STATUSES.join("|")})`);
    }
  }
  return e;
}

const tagLine = (doc, line) => ({ ...doc, line });
const isAdrFile = (f) => /\/\d{3}-/.test(f.replace(/\\/g, "/"));

export function loadAdrs() {
  const load = (dir, line) =>
    listMarkdown(dir, ["README.md"])
      .filter(isAdrFile)
      .map((f) => tagLine(parseDoc(f), line))
      .sort(byId);
  // Core line first, then the project line (both indexed by the same generator).
  return [...load(ADR_DIR, "core"), ...load(ADR_PROJECT_DIR, "project")];
}
export function loadRules() {
  const core = listMarkdown(RULES_DIR, ["INDEX.md"]).map((f) => tagLine(parseDoc(f), "core"));
  const project = listMarkdown(RULES_PROJECT_DIR, ["README.md"]).map((f) =>
    tagLine(parseDoc(f), "project"),
  );
  return [...core.sort(byId), ...project.sort(byId)];
}
export function loadMemory() {
  return listMarkdown(MEMORY_DIR, ["README.md", "MEMORY.md"]).map(parseDoc).sort(byId);
}
function byId(a, b) {
  return String(a.data.id).localeCompare(String(b.data.id), "en", { numeric: true });
}

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|");

/** docs/adr/manifest.json (machine index). */
export function genAdrManifest(adrs) {
  const entries = adrs.map((d) => ({
    id: d.data.id,
    title: d.data.title,
    tldr: d.data.tldr,
    scope: d.data.scope,
    load: d.data.load,
    status: d.data.status,
    triggers: d.data.triggers ?? [],
    "applies-to": d.data["applies-to"] ?? [],
    supersededBy: d.data["superseded-by"] ?? null,
    path: d.rel,
    hash: d.hash,
  }));
  return JSON.stringify({ generated: true, count: entries.length, adrs: entries }, null, 2) + "\n";
}

/** docs/adr/README.md (human index). */
export function genAdrReadme(adrs) {
  const rows = adrs
    .map(
      (d) =>
        `| [${d.data.id}](${path.relative(ADR_DIR, d.file).split(path.sep).join("/")}) | ${esc(d.data.title)} | ${esc(d.data.tldr)} | ${d.data.status} | ${d.data.load} |`,
    )
    .join("\n");
  return `${GENERATED_NOTICE}

# Architecture Decision Records

Every agent MUST read the ADRs relevant to its task before changing code. ADRs document **why**
decisions were made. Loading follows the contract in \`.claude/rules/context-loading.md\` and ADR-006:
always read \`load: core\`; read \`conditional\` when scope/triggers match; read \`archival\` only on
demand.

This index and \`manifest.json\` are generated from the ADR front-matter by \`scripts/sync-index.mjs\`.
Run \`npm run governance:sync\` after adding or editing an ADR; \`npm run governance:check\` enforces it.

## Format

\`\`\`
# ADR-NNN: Title
- Status / Date / Metadata (scope, load, triggers, applies-to, supersedes)
- Context / Decision / Alternatives / Consequences / References
\`\`\`

## Index

| ADR | Title | TL;DR | Status | Load |
| --- | --- | --- | --- | --- |
${rows}
`;
}

/** docs/adr/current/README.md (operational snapshot of accepted ADRs). */
export function genAdrCurrent(adrs) {
  const accepted = adrs.filter((d) => d.data.status === "accepted");
  const rows = accepted
    .map(
      (d) =>
        `| [${d.data.id}](../${path.relative(ADR_DIR, d.file).split(path.sep).join("/")}) | ${esc(d.data.title)} | ${d.data.load} |`,
    )
    .join("\n");
  return `${GENERATED_NOTICE}

# Current ADRs (accepted snapshot)

${accepted.length} accepted decisions. Superseded/deprecated ADRs are omitted here; see the full index
in [../README.md](../README.md).

| ADR | Title | Load |
| --- | --- | --- |
${rows}
`;
}

/** .claude/rules/INDEX.md (rule TLDR bootstrap list). */
export function genRulesIndex(rules) {
  const rows = rules
    .map(
      (d) =>
        `| [${esc(d.data.id)}](${path.relative(RULES_DIR, d.file).split(path.sep).join("/")}) | ${esc(d.data.tldr)} | ${d.data.load} | ${(d.data.triggers ?? []).join(", ")} |`,
    )
    .join("\n");
  return `${GENERATED_NOTICE}

# Rules index

Generated from rule front-matter by \`scripts/sync-index.mjs\`. Always load \`core\` rules; load others
when their triggers/applies-to match (see \`context-loading.md\`).

| Rule | TL;DR | Load | Triggers |
| --- | --- | --- | --- |
${rows}
`;
}

/** .claude/memory/MEMORY.md (memory index). */
export function genMemoryIndex(memos) {
  const rows = memos
    .map((d) => `- [${esc(d.data.title)}](${path.basename(d.rel)}) — ${esc(d.data.tldr)}`)
    .join("\n");
  return `${GENERATED_NOTICE}

# Memory index

Repo-resident agent memory (ADR-003). Generated by \`scripts/sync-index.mjs\`; see
[README.md](README.md) for what belongs here.

${rows}
`;
}

/** Replace the body between AUTO-GENERATED:<name> START/END markers. */
export function replaceMarkerBlock(text, name, body) {
  const start = new RegExp(`(<!-- AUTO-GENERATED:${name} START[^>]*-->)`);
  const end = new RegExp(`(<!-- AUTO-GENERATED:${name} END -->)`);
  const ms = text.match(start);
  const me = text.match(end);
  if (!ms || !me) throw new Error(`marker block '${name}' not found in blueprint`);
  const before = text.slice(0, ms.index + ms[0].length);
  const after = text.slice(me.index);
  return `${before}\n${body}\n${after}`;
}

/** Compact tables embedded into the blueprint Part A. */
export function genBlueprintAdrBlock(adrs) {
  const rows = adrs
    .map((d) => `| ${d.data.id} | ${esc(d.data.tldr)} | ${d.data.load} |`)
    .join("\n");
  return `\n| ADR | TL;DR | Load |\n| --- | --- | --- |\n${rows}\n`;
}
export function genBlueprintRulesBlock(rules) {
  const rows = rules
    .map((d) => `| ${esc(d.data.id)} | ${esc(d.data.tldr)} | ${d.data.load} |`)
    .join("\n");
  return `\n| Rule | TL;DR | Load |\n| --- | --- | --- |\n${rows}\n`;
}

/** Compute every generated artefact as { path, content }. Pure — no writes.
 *
 * The portable governance blueprint (`docs/agent-governance-blueprint.md`) is maintained in the
 * source repo this system was born in; downstream projects that adopt the system don't carry it.
 * If it's absent here, we simply skip its auto-generated index blocks. */
export function computeArtifacts() {
  const adrs = loadAdrs();
  const rules = loadRules();
  const memos = loadMemory();

  const artifacts = [
    { path: path.join(ADR_DIR, "manifest.json"), content: genAdrManifest(adrs) },
    { path: path.join(ADR_DIR, "README.md"), content: genAdrReadme(adrs) },
    { path: path.join(ADR_DIR, "current", "README.md"), content: genAdrCurrent(adrs) },
    { path: path.join(RULES_DIR, "INDEX.md"), content: genRulesIndex(rules) },
    { path: path.join(MEMORY_DIR, "MEMORY.md"), content: genMemoryIndex(memos) },
  ];

  if (fs.existsSync(BLUEPRINT)) {
    let blueprint = fs.readFileSync(BLUEPRINT, "utf8");
    blueprint = replaceMarkerBlock(blueprint, "adr-index", genBlueprintAdrBlock(adrs));
    blueprint = replaceMarkerBlock(blueprint, "rules-index", genBlueprintRulesBlock(rules));
    artifacts.push({ path: BLUEPRINT, content: blueprint });
  }

  return { adrs, rules, memos, artifacts };
}

/**
 * Collect the governance ids a document cites in its BODY — `ADR-NNN` and `rule:<slug>` — excluding its
 * own id. These bare citations are how the rules and ADRs actually reference each other in prose, so a
 * layer gate that only looked at markdown links (ADR-033) would miss most of the dependencies it exists
 * to police: `core-principles.md` cites ADR-026 in plain text, not as a link.
 *
 * Front-matter is skipped on purpose: `id`, `supersedes` and `superseded-by` are metadata about the
 * document, not dependencies of it.
 */
export function collectIdRefs(file) {
  const { data, content } = matter(fs.readFileSync(file, "utf8"));
  const self = String(data.id ?? "");
  const found = new Set();
  for (const [re, prefix] of [
    [/\bADR-\d{3}\b/g, ""],
    [/\brule:[a-z0-9][a-z0-9-]*/g, ""],
  ]) {
    for (const m of content.matchAll(re)) found.add(prefix + m[0]);
  }
  found.delete(self);
  return [...found];
}

/** Collect markdown links of the form [text](relative.md...) from a file, return absolute targets. */
export function collectLinks(file) {
  const text = fs.readFileSync(file, "utf8");
  const out = [];
  const re = /\]\(([^)]+\.md)(#[^)]*)?\)/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    const target = m[1];
    if (/^https?:/.test(target)) continue;
    out.push({ target, abs: path.resolve(path.dirname(file), target) });
  }
  return out;
}
